In [1]:
import numpy as np

In [7]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [27]:
b=np.ones((3,3),dtype=np.float32)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
c=np.zeros((3,3),dtype=np.double)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
d=np.arange(0,50,3)
print(d)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [29]:
e=np.concatenate([b,c])
print(e)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
f=e.astype(np.int16)
print(f)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [33]:
g=f.astype(np.double)
print(g)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [50]:
h=np.random.random((3,4))
j=h.reshape(12,1)
print(h)
print()
print(j)

[[0.70796962 0.42635988 0.91135351 0.68893183]
 [0.67320083 0.60304681 0.3453366  0.47858973]
 [0.64630854 0.04986576 0.71432678 0.83474106]]

[[0.70796962]
 [0.42635988]
 [0.91135351]
 [0.68893183]
 [0.67320083]
 [0.60304681]
 [0.3453366 ]
 [0.47858973]
 [0.64630854]
 [0.04986576]
 [0.71432678]
 [0.83474106]]
